Repository Team-inglo/Giggle, pull requests merged in 2024-08, with the labels that each got.

#34 Fix/#33 모두싸인 api 데이터 미리 삽입 부분 추가, webhook url 변경
  src/main/java/com/inglo/giggle/constants/Constants.java
  src/main/java/com/inglo/giggle/domain/Document.java
  src/main/java/com/inglo/giggle/dto/request/WebClientRequestDto.java
  src/main/java/com/inglo/giggle/service/AnnouncementService.java
  src/main/java/com/inglo/giggle/service/DocumentService.java
Labels: bug, 은지, fix

#35 Fix/#33 아르바이트 공고 추천 알고리즘 보완 / 모두싸인 webhook url 변경, 서류 리스트 조회에 apply id response 추가
  src/main/java/com/inglo/giggle/constants/Constants.java
  src/main/java/com/inglo/giggle/controller/DocumentController.java
  src/main/java/com/inglo/giggle/dto/response/UserApplyLogDto.java
  src/main/java/com/inglo/giggle/service/AnnouncementService.java
  src/main/java/com/inglo/giggle/service/ApplyService.java
Labels: fix

#37 🚑 Fix/#36 전자 문서 작성 시 필요한 데이터 추가 / 버그 수정
  src/main/java/com/inglo/giggle/domain/Applicant.java
  src/main/java/com/inglo/giggle/dto/request/UpdateApplicantDto.java
  src/main/java/com/inglo/giggle/dto/request/WebHookRequestDto.java
  src/main/java/com/inglo/giggle/service/AnnouncementService.java
  src/main/java/com/inglo/giggle/service/ApplyService.java
  src/main/java/com/inglo/giggle/service/DocumentService.java
Labels: bug, 동겸
